# argocd/wireguard/peer-job.yaml
# ...
      containers:
      - name: peer-updater
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        # Inicia el bloque args. La línea con el guion (-) es clave.
        args:
          - |
            # 1. Definir la nueva cantidad de peers deseada
            NEW_PEER_COUNT="6"
            DEPLOYMENT_NAME="wireguard-server"
            NAMESPACE="wireguard"
            
            echo "Parcheando Deployment $DEPLOYMENT_NAME con PEERS=$NEW_PEER_COUNT..."
            
            # Usando el parche Strategic Merge Patch más robusto (sin índice)
            kubectl patch deployment $DEPLOYMENT_NAME -n $NAMESPACE \
              --type='merge' \
              --patch '{"spec":{"template":{"spec":{"containers":[{"name":"wireguard", "env":[{"name":"PEERS", "value": "'$NEW_PEER_COUNT'"}]}]}}}}'
              
            echo "Parche aplicado. El Deployment se reiniciará."
