# argocd/wireguard/peer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # CORRECCIÓN 1: generateName debe terminar con un guion (-)
  generateName: wireguard-peer-updater-
  namespace: wireguard
spec:
  # CORRECCIÓN ADICIONAL: backoffLimit para manejar fallos
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: peer-scaler-sa
      restartPolicy: OnFailure
      containers:
      - name: peer-updater
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            # 1. Definir la nueva cantidad de peers deseada (¡EDITAR ESTE VALOR EN GIT!)
            NEW_PEER_COUNT="6"
            DEPLOYMENT_NAME="wireguard-server"
            NAMESPACE="wireguard"
            
            echo "Parcheando Deployment $DEPLOYMENT_NAME con PEERS=$NEW_PEER_COUNT..."
            
            # 2. Parche JSON para reemplazar el valor de la variable PEERS (índice 5)
            # CORRECCIÓN 2: Índice cambiado a 5 para apuntar a PEERS.
            kubectl patch deployment $DEPLOYMENT_NAME \
              --namespace $NAMESPACE \
              --type='json' \
              -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/env/5", "value": {"name": "PEERS", "value": "'$NEW_PEER_COUNT'"}}]'
              
            echo "Parche aplicado. El Deployment se reiniciará."
