# argocd/wireguard/peer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # CORRECCIÓN 1: generateName debe terminar con un guion (-)
  generateName: wireguard-peer-updater-
  namespace: wireguard
spec:
  # CORRECCIÓN ADICIONAL: backoffLimit para manejar fallos
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: peer-scaler-sa
      restartPolicy: OnFailure
      containers:
      - name: peer-updater
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
          args:
          - |
            # 1. Definir la nueva cantidad de peers deseada (¡EDITAR ESTE VALOR EN GIT!)
            NEW_PEER_COUNT="6"
            DEPLOYMENT_NAME="wireguard-server"
            NAMESPACE="wireguard"
            
            echo "Parcheando Deployment $DEPLOYMENT_NAME con PEERS=$NEW_PEER_COUNT..."
            
            # 2. Usar 'Strategic Merge Patch' para reemplazar la variable de entorno PEERS. 
            #    Este método encuentra la ENV por nombre, no por índice de array.
            kubectl patch deployment $DEPLOYMENT_NAME -n $NAMESPACE \
              --patch '{"spec":{"template":{"spec":{"containers":[{"name":"wireguard", "env":[{"name":"PEERS", "value": "'$NEW_PEER_COUNT'"}]}]}}}}'
              
            echo "Parche aplicado. El Deployment se reiniciará."
