apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-exporter
  template:
    metadata:
      labels:
        app: zabbix-exporter
    spec:
      containers:
      - name: zabbix-exporter
        image: kostex/zabbix-prometheus-exporter:latest
        ports:
        - containerPort: 9116
        env:
        - name: ZBX_SERVER
          value: "https://zabbix60.innovation.es/zabbix/api_jsonrpc.php"
        - name: ZBX_USERNAME
          value: "sistemas"
        - name: ZBX_PASSWORD
          value: "1nn0v4t10n"
        - name: PORT
          value: "9116"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-exporter
  namespace: default
spec:
  type: NodePort
  selector:
    app: zabbix-exporter
  ports:
  - protocol: TCP
    port: 9116
    targetPort: 9116
    nodePort: 30005
