apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard-peer-creator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hipocrita/k3s.git
    targetRevision: main
    path: argocd/wireguard
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  # Prune para que Argo CD borré el job cuando esté completado
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
