apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/robertocg/grafana.git
    targetRevision: main
    path: prometheus  # Cambia este path según donde hayas almacenado los archivos YAML
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Usa el namespace donde desees desplegar Prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
