apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/robertocg/k3s.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
