# wireguard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-server
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/Madrid
        - name: SERVERURL
          value: 79.112.74.227 # La IP pública que el cliente usará
        - name: SERVERPORT
          value: "51820"
        - name: PEERS
          value: "5" # Número de dispositivos
        - name: PEERDNS
          value: "192.168.1.2" # DNS del clúster
        - name: ALLOWEDIPS
          value: "0.0.0.0/0" # Acceso a todo el clúster (Pods y Services)
        - name: INTERNAL_SUBNET
          value: "10.9.0.0" # La red interna del túnel VPN
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wireguard-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
  namespace: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1 # Exposicion puerto UDP 51820
kind: Service
metadata:
  name: wireguard-svc
  namespace: wireguard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: wireguard
  ports:
  - name: wireguard-udp
    protocol: UDP
    port: 51820
    targetPort: 51820
