# jenkins-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30200  # Asegúrate de establecer tu puerto deseado aquí
  selector:
    app.kubernetes.io/component: jenkins
