apiVersion: v1
kind: Pod
metadata:
  name: ansible-pod
  namespace: argocd
  labels:
    app: ansible
spec:
  containers:
  - name: ansible
    image: cytopia/ansible:latest
    command: ["sleep", "infinity"]
    ports:
    - containerPort: 80
