apiVersion: v1
kind: Service
metadata:
  name: ansible-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: ansible
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
